name: Build and Release
on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Setup Ninja
              uses: seanmiddleditch/gha-setup-ninja@v5
                
            - name: Build Project
              uses: threeal/cmake-action@v2.1.0
              with:
                build-dir: out/build
                generator: Ninja
                cxx-compiler: clang++
                c-compiler: clang
                cxx-flags: -std=c++20
                options: CMAKE_BUILD_TYPE=Release

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: NotVim-Winx64-Release
                path: ./out/build/nve.exe

    release:
        runs-on: windows-latest
        needs: [ build ]
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7

            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: NotVim-Winx64-Release
                path: ./out/build/nve.exe

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                prerelease: true
                name: v0.6.0a - Syntax Config File
                tag: v0.6.0a
                artifacts: NotVim-Winx64-Release
