name: Build and Release
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Setup Ninja
              uses: seanmiddleditch/gha-setup-ninja@v5
                
            - name: Build Project
              uses: threeal/cmake-action@v2.1.0
              with:
                build-dir: out/build
                generator: Ninja
                cxx-compiler: clang++
                cxx-flags: -std=c++20
                options: CMAKE_BUILD_TYPE=Release

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: ./dist

    release:
        runs-on: windows-latest
        needs: [ build ]

        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: my-artifact
                path: ./dist
            - name: Create Release
              uses: actions/create-release@v1
              with:
                tag_name: ${{ github.ref_name }}
                release_name: Release ${{ github.ref_name }}
                draft: false
                prerelease: false
                body: |
                    Release notes
            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              with:
                upload_url: ${{ github.ref_name }}
                asset_path: ./dist
                asset_name: my-artifact.zip
                asset_content_type: application/zip
            - name: Publish Release
              uses: actions/publish-release@v1
              with:
                path: ./dist