name: Build and Release
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Setup Ninja
              uses: seanmiddleditch/gha-setup-ninja@v5
                
            - name: Build Project
              uses: threeal/cmake-action@v2.1.0
              with:
                build-dir: out/build
                generator: Ninja
                cxx-compiler: clang++
                c-compiler: clang
                cxx-flags: -std=c++20
                options: CMAKE_BUILD_TYPE=Release

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: NotVim-Winx64-Release
                path: ./out/build/nve.exe

    release:
        runs-on: windows-latest
        needs: [ build ]

        steps:
            - uses: actions/checkout@v4.1.7
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: NotVim-Winx64-Release
                path: ./out/build/nve.exe
            - name: Create Release
              uses: marvinpinto/action-automatic-releases@latest
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                automatic_release_tag: latest
                title: v0.5.0a
                prerelease: true
                files: |
                    ./out/build/nve.exe
