name: Build And Test
on:
  push:
    branches: [ master, dev ]

jobs:
  build-project:
    name: Build And Run Tests
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4.1.7
      
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Build Tests
      uses: threeal/cmake-action@v2.1.0
      with:
        build-dir: out/build
        generator: Ninja
        cxx-compiler: g++-13
        cxx-flags: -std=c++20
        options: BUILD_TESTS=ON BUILD_PROJECT=OFF

    - name: Run Tests
      run: cd ./out/build/tests && ./Tests --gtest_filter=-Console*:Editor*:Input*
