name: Create Release
on:
    push:
        branches: [ release ]

jobs:
    release:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7

            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                name: Mini-Winx64-Release
                path: out/build

            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                prerelease: true
                name: v0.7.0a - Massive performance improvement for large files
                tag: v0.7.0a
