name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@v5

    - name: Build Project
      uses: threeal/cmake-action@v2.0.0
      with:
        source-dir: source
        build-dir: out/build
        generator: Ninja
        cxx-compiler: g++
        cxx-flags: -std=c++20
        options: CMAKE_BUILD_TYPE=Release
